### ISSUE TITLE
You can listen to it using Pocketcasts or Player FM

### ISSUE THREAD

**Issue by orschiro** [adelnizamutdinov/youtube-rss#15]
Suggestion to add link to [Player FM](https://player.fm/) another great free online web player. 

What do you think? :-)

![screenshot from 2018-02-21 15-53-46](https://user-images.githubusercontent.com/170947/36486761-9a31713e-171f-11e8-8167-a925805697b8.png)

**Comment by adelnizamutdinov** [comment]
yeah no prob, I'll add it

**Comment by adelnizamutdinov** [comment]
fixed in https://github.com/adelnizamutdinov/youtube-rss/commit/726fa107de9207bb41e3200c297fcba509955265

**Comment by orschiro** [comment]
@adelnizamutdinov thanks!
