### ISSUE TITLE
Ability to convert media library?

### ISSUE THREAD

**Issue by orschiro** [adelnizamutdinov/youtube-rss#16]
Hey @adelnizamutdinov,

Do you see any possibility converting the following RSS video feed into a valid podcast feed?

https://www.zdf.de/rss/zdf/comedy/heute-show

Thank you!

**Comment by adelnizamutdinov** [comment]
Hey! Not interested in that, really

**Comment by orschiro** [comment]
@adelnizamutdinov ok, thanks though for the fast reply!
