### ISSUE TITLE
get rid of the 50 item limit

### ISSUE THREAD

**Issue by adelnizamutdinov** [adelnizamutdinov/youtube-rss#4]

**Comment by orschiro** [comment]
+1 on this one. Wasn't aware actually of this limit. Subscribed to a channel and wanted to go back to one of the older videos but couldn't find it because the list stops at 50 entries. 

Would be really great if you can make this work!

**Comment by adelnizamutdinov** [comment]
should be fixed in https://github.com/adelnizamutdinov/youtube-rss/commit/16ea442d14566ceb2c1c0d611e803ec2f6827c63

but it blows up on playlists with 2k items, but I can deal with that later

**Comment by orschiro** [comment]
@adelnizamutdinov thanks for the implementation! Going to text and give you feedback. :-)

Do I need to re-add the feed or will the existing one be refreshed and updated accordingly?

**Comment by adelnizamutdinov** [comment]
@orschiro it should be refreshed. Depends on your podcast player, though

**Comment by adelnizamutdinov** [comment]
@orschiro I mean your player should be able to refresh the existing one automatically

**Comment by orschiro** [comment]
OK thanks! Going to check if Player FM does that automatically...
